### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tombensve** [tombensve/APS#31]
This is a very generic TODO for things that needs doing anywhere in the project.

- [ ] All services should be based on ServiceLoader.
  - [ ] Use googles annotation.

- [ ] Redo APSBus as a class calling APSBusRouter implementations.

**Comment by tombensve** [comment]
Cancelled.
